#! /bin/bash
# darqos
# Copyright (C) 2023-2024, David Arnold

# Make a distribution snapshot

EDITION='1'

rm -rf dist
mkdir -p "dist/darq"

root=$(pwd)
destdir="$root/dist/darq"

# Runtime package.
rm -rf dist
python -m build
mkdir -p "$destdir/lib"
cp -p dist/darq-*-py3-none-any.whl "$destdir/lib/"
echo "darq.whl"

# p-Kernel.
mkdir -p "$destdir/kernel"
cp -p "$root"/kernel/*.py "$destdir/kernel/"
cp -p "$root"/kernel/darqos-pkernel "$destdir/kernel/"
cp -p "$root"/kernel/darqos-pkernel.service "$destdir/kernel/"
cp -p "$root"/kernel/darqos.target "$destdir/kernel/"
echo "kernel"

# Services.
mkdir -p "$destdir/services"
for f in "$root"/services/*/*.py "$root"/services/*/darqos-* ; do
  t=${f#"$root"}
  mkdir -p `dirname $destdir/$t`
  cp -p $f $destdir/$t
  echo $t
done

# Types.
mkdir -p "$destdir/types"
for f in `find "$root/types" -name "*.py" -print`; do
  t=${f#"$root"}
  mkdir -p `dirname $destdir/$t`
  cp -p $f $destdir/$t
  echo $t
done

# Lenses.
mkdir -p "$destdir/lenses"
for f in `find "$root/lenses" -name "*.py" -print`; do
  t=${f#"$root"}
  mkdir -p `dirname $destdir/$t`
  cp -p $f $destdir/$t
  echo $t
done

# System scripts.
mkdir -p "$destdir/sys"
for f in `find "$root/sys" -name "*" -print`; do
  t=${f#"$root"}
  mkdir -p `dirname $destdir/$t`
  cp -p $f $destdir/$t
  echo $t
done

# Make archive.
name=darqos-${EDITION}ed-snap`date +%Y%m%d`.tar
rm -f $name.gz

cd dist
export COPYFILE_DISABLE=1
tar cvf ../$name darq
cd ..
gzip -9 $name

# Cleanup.
rm -rf dist
